(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var aa=this||self;function m(a,b){a=a.split(".");var c=aa;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}:c[d]=b};var n={},p=null;
function q(a){var b;void 0===b&&(b=0);if(!p){p={};for(var c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),d=["+/=","+/","-_=","-_.","-_"],f=0;5>f;f++){var e=c.concat(d[f].split(""));n[f]=e;for(var g=0;g<e.length;g++){var k=e[g];void 0===p[k]&&(p[k]=g)}}}b=n[b];c=Array(Math.floor(a.length/3));d=b[64]||"";for(f=e=0;e<a.length-2;e+=3){var l=a[e],h=a[e+1];k=a[e+2];g=b[l>>2];l=b[(l&3)<<4|h>>4];h=b[(h&15)<<2|k>>6];k=b[k&63];c[f++]=g+l+h+k}g=0;k=d;switch(a.length-e){case 2:g=
a[e+1],k=b[(g&15)<<2]||d;case 1:a=a[e],c[f]=b[a>>2]+b[(a&3)<<4|g>>4]+k+d}return c.join("")};var r="undefined"!==typeof Uint8Array,t={};let v;var w=class{constructor(a){if(t!==t)throw Error("illegal external caller");this.A=a;if(null!=a&&0===a.length)throw Error("ByteString should be constructed with non-empty values");}};const x=Symbol();function y(a,b){x?a[x]|=b:void 0!==a.m?a.m|=b:Object.defineProperties(a,{m:{value:b,configurable:!0,writable:!0,enumerable:!1}})}function z(a){let b;x?b=a[x]:b=a.m;return null==b?0:b}function A(a,b){x?a[x]=b:void 0!==a.m?a.m=b:Object.defineProperties(a,{m:{value:b,configurable:!0,writable:!0,enumerable:!1}})}function B(a){return!!(z(a)&2)}function C(a){y(a,16);return a}function ba(a){y(a,48);return a}function ca(a){const b=z(a);A(a,b|32);return!!(b&32)}
function da(a,b){A(b,(z(a)|18)&-41)};var D={};function E(a){return null!==a&&"object"===typeof a&&!Array.isArray(a)&&a.constructor===Object}var F;const G=[];A(G,23);F=Object.freeze(G);function H(a){if(B(a.j))throw Error("Cannot mutate an immutable Message");}function I(a){var b=a.length;(b=b?a[b-1]:void 0)&&E(b)?b.g=1:a.push({g:1})};let J;function K(a,b){J=b;a=new a(b);J=void 0;return a};function ea(a){switch(typeof a){case "number":return isFinite(a)?a:String(a);case "object":if(a)if(Array.isArray(a)){if(0!==(z(a)&128))return a=Array.prototype.slice.call(a),I(a),a}else{if(r&&null!=a&&a instanceof Uint8Array)return q(a);if(a instanceof w){const b=a.A;return null==b?"":"string"===typeof b?b:a.A=q(b)}}}return a};function L(a,b,c,d){if(null!=a){if(Array.isArray(a))a=M(a,b,c,void 0!==d);else if(E(a)){const f={};for(let e in a)f[e]=L(a[e],b,c,d);a=f}else a=b(a,d);return a}}function M(a,b,c,d){d=d?!!(z(a)&16):void 0;const f=Array.prototype.slice.call(a);for(let e=0;e<f.length;e++)f[e]=L(f[e],b,c,d);c(a,f);return f}function fa(a){return a.u===D?a.toJSON():ea(a)}function ha(a,b){0!==(z(a)&128)&&I(b)};function N(a){return a.h||(a.h=a.j[a.i+a.s]={})}function O(a,b,c,d=!1,f=!1){f||H(a);a.l&&(a.l=void 0);b>=a.i||d?N(a)[b]=c:(a.j[b+a.s]=c,(a=a.h)&&b in a&&delete a[b])}function P(a,b,c){var d=-1===c?null:c>=a.i?a.h?a.h[c]:void 0:a.j[c+a.s];{let e=!1;var f=null==d||"object"!==typeof d||(e=Array.isArray(d))||d.u!==D?e?new b(d):void 0:d}f!==d&&null!=f&&(O(a,c,f,!1,!0),y(f.j,z(a.j)&-33));b=f;if(null==b)return b;B(b.j)&&!B(a.j)&&(B(b.j)&&(d=Q(b),d.l=b,b=d),O(a,c,b,!1));return b}
function R(a,b,c,d){H(a);if(null!=c){var f=[];y(f,1);let e=!1;for(let g=0;g<c.length;g++)f[g]=c[g].j,e=e||B(f[g]);a.o||(a.o={});a.o[b]=c;c=f;e?x?c[x]&&(c[x]&=-9):void 0!==c.m&&(c.m&=-9):y(c,8)}else a.o&&(a.o[b]=void 0),f=F;O(a,b,f,d)};function S(a){if(B(a)&&Object.isFrozen(a))return a;const b=Array.prototype.map.call(a,T,void 0);A(b,(z(a)|18)&-41);Object.freeze(b);return b}function U(a,b){if(null!=a){if(r&&a instanceof Uint8Array)return a.length?new w(new Uint8Array(a)):v||(v=new w(null));if(Array.isArray(a)){if(B(a))return a;b&&(b=z(a),b=!(b&32)&&(!!(b&16)||0===b));if(b)return y(a,2),a;a=M(a,U,da);z(a)&4&&Object.freeze(a);return a}return a.u===D?T(a):a}}function T(a){if(B(a.j))return a;a=Q(a);y(a.j,2);return a}
function Q(a){const b=a.j;var c=C([]),d=a.constructor.h;d&&c.push(d);0!==(z(b)&128)&&I(c);c=K(a.constructor,c);a.v&&(c.v=a.v.slice());d=!!(z(b)&16);for(let h=0;h<b.length;h++){var f=b[h];if(h===b.length-1&&E(f))for(const u in f){var e=+u;if(Number.isNaN(e))N(c)[e]=f[e];else{var g=c,k=f[u],l=d;const Z=a.o&&a.o[e];Z?R(g,e,S(Z),!0):O(g,e,U(k,l),!0)}}else g=c,e=h-a.s,k=d,(l=a.o&&a.o[e])?R(g,e,S(l),!1):O(g,e,U(f,k),!1)}return c};function ia(a,b){if(null==b||""==b)return new a;b=JSON.parse(b);if(!Array.isArray(b))throw Error(void 0);return K(a,C(b))}
var V=class{constructor(a,b,c){null==a&&(a=J);J=void 0;var d=this.constructor.i||0,f=0<d,e=this.constructor.h;let g=!1,k=!1;if(null==a)a=ba(e?[e]:[]),g=!0;else{if(!Array.isArray(a))throw Error();if(e&&e!==a[0])throw Error();if(g=!!(z(a)&16))k=ca(a);if(f)if(0!==(z(a)&128))d=0;else if(0<a.length){const l=a[a.length-1];if(E(l)&&"g"in l){d=0;y(a,128);delete l.g;let h=!0;for(let u in l){h=!1;break}h&&a.pop()}}}this.s=(e?0:-1)-d;this.o=void 0;this.j=a;ja(this,b);if(!f){if(this.h&&"g"in this.h)throw Error('Unexpected "g" flag in sparse object of message that is not a group type.');
if(0!==(z(a)&128))throw Error();}if(c){const l=1|(g&&!k?16:0);a=h=>{if(Array.isArray(h)){const u=z(h);(u&l)===l||Object.isFrozen(h)||A(h,u|l)}};for(b=0;b<c.length;b++)d=c[b],d<this.i?(d+=this.s,(f=this.j[d])?a(f):this.j[d]=F):(f=N(this),(e=f[d])?a(e):f[d]=F)}}toJSON(){return M(this.j,fa,ha)}};function ja(a,b){var c=a.j.length;const d=c-1;if(c&&(c=a.j[d],E(c))){a.h=c;a.i=d-a.s;return}void 0!==b&&-1<b?(a.i=Math.max(b,d+1-a.s),a.h=void 0):a.i=Number.MAX_VALUE}V.prototype.u=D;V.prototype.toString=function(){return this.j.toString()};var la=class extends V{constructor(a){super(a,-1,ka)}},ka=[8];var na=class extends V{constructor(a){super(a,-1,ma)}},ma=[17];var pa=class extends V{constructor(a){super(a,-1,oa)}},oa=[27];var qa=class extends V{constructor(a){super(a)}};var sa=class extends V{constructor(a){super(a,-1,ra)}},ra=[1,2,3,6];function W(a,b){a=a.getElementsByTagName("META");for(let c=0;c<a.length;++c)if(a[c].getAttribute("name")===b)return a[c].getAttribute("content")||"";return""};function X(a,b){a=a.body;var c={detail:void 0};let d;"function"===typeof window.CustomEvent?d=new CustomEvent(b,c):(d=document.createEvent("CustomEvent"),d.initCustomEvent(b,!!c.bubbles,!!c.cancelable,c.detail));a.dispatchEvent(d)}
var ta=class{constructor(a){this.body=a;this.h=[];W(a,"sampling_mod");var b=W(a,"namespace");if(!b){b="ns-"+(0,Math.random)().toString(36).substr(2,5);a:{var c=a.getElementsByTagName("META");for(let d=0;d<c.length;++d)if("namespace"===c[d].getAttribute("name")&&c[d].getAttribute("index")===(0).toString()){c[d].setAttribute("content",b);break a}c=a.querySelector("#mys-meta");c||(c=document.createElement("div"),c.id="mys-meta",c.style.position="absolute",c.style.display="none",a.appendChild(c));a=document.createElement("META");
a.setAttribute("name","namespace");a.setAttribute("content",b);a.setAttribute("index",(0).toString());c.appendChild(a)}}if(!(0<this.h.length)){a=W(this.body,"environment");for(const d of a.split("|"))d&&this.h.push(d)}}addEventListener(a,b){this.body.addEventListener(a,b)}};function ua(a){var b=document;a=String(a);"application/xhtml+xml"===b.contentType&&(a=a.toLowerCase());return b.createElement(a)};function va(a){if(1>=a.i.offsetWidth||1>=a.i.offsetHeight)return!1;a.h.remove();X(a.context,"spanReady");return!0}
var wa=class{constructor(a){this.context=a;this.l={C:!1,B:100};this.i=ua("SPAN");this.h=ua("DIV");this.i.style.fontSize="6px";this.i.textContent="go";this.h.style.position="absolute";this.h.style.top="100%";this.h.style.left="100%";this.h.style.width="1px";this.h.style.height="0";this.h.style.overflow="hidden";this.h.style.visibility="hidden";this.h.appendChild(this.i)}wait(){if(!this.l.C&&(X(this.context,"spanStart"),this.context.body.appendChild(this.h),!va(this)))return new Promise(a=>{const b=
setInterval(()=>{va(this)&&(clearInterval(b),a())},this.l.B)})}};var xa=class{constructor(a,b){this.context=a;this.h=P(b,pa,1)||new pa;P(b,la,12)||new la;P(this.h,na,10)||new na}};function ya(a){a.l.length=0;a.i=!0}function za(a,b){a.h=!0;const c=()=>{a.i=!1;const d=a.l.shift();return void 0===d?(a.h=!1,Promise.resolve()):za(a,d())};return b?b.then(c,()=>{if(a.i)return c();a.h=!1;return Promise.reject()}):c()}function Aa(a,b){for(const c of b)a.l.push(c);if(!a.h)return za(a)}var Ba=class{constructor(){this.i=this.h=!1;this.l=[]}};function Ca(a){var b=W(a.context.body,"render_config")||"[]";b=ia(qa,b);return new xa(a.context,b)}function Da(a){ya(a.l);return Aa(a.l,[()=>{let b;a.i||(a.i=Ca(a));b=(new wa(a.context)).wait();X(a.context,"browserStart");X(a.context,"browserStartEnd");a.h&=-31;a.h|=2;return b},()=>{X(a.context,"browserReady");X(a.context,"browserReadyEnd");a.h|=4;X(a.context,"overallReady")},()=>{X(a.context,"browserQuiet");X(a.context,"browserQuietEnd");a.h|=8}])}
function Ea(a){ia(sa,W(a.context.body,"engine_msg")||"[]");return Da(a)||Promise.resolve()}function Fa(){var a=Y;a.h&=-31;a.h|=1;let b=0;const c=a.context.body;c.addEventListener("browserRender",()=>{++b;if(1===b)X(a.context,"overallStart"),Ea(a).then(()=>{X(a.context,"overallQuiet")});else{var d=c.clientHeight;c.clientWidth&&d&&(a.i||(a.i=Ca(a)),Ea(a))}})}var Ga=class{constructor(a){this.l=new Ba;this.h=0;this.context=new ta(a)}};let Y;m("mys.engine.init",(a,b)=>{Y=new Ga(b);Fa()});m("mys.engine.stage",()=>{let a;return(null==(a=Y)?void 0:a.h)||0});}).call(this);
